# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifEylxI_9rJLwY6QswpZS3dFZcV0kGhN
"""

# -*- coding: utf-8 -*-
import streamlit as st

# --- Define the directed graph (based on your image) ---
graph = {
    'A': ['B', 'D'],
    'B': ['C', 'E', 'G'],
    'C': ['A'],
    'D': ['C'],
    'E': ['H'],
    'F': [],
    'G': ['F'],
    'H': ['F', 'G']
}

# --- DFS function ---
def dfs(graph, start, visited=None):
    if visited is None:
        visited = []
    visited.append(start)

    for neighbor in sorted(graph[start]):  # alphabetical order
        if neighbor not in visited:
            dfs(graph, neighbor, visited)
    return visited

# --- Streamlit interface ---
st.title("Depth-First Search (DFS) Traversal")
st.write("This app performs **Depth-First Search (DFS)** on the directed graph shown below.")

# --- Display the graph image ---
st.image("LabReport_BSD2513_#1.jpg", caption="Graph Used for DFS", use_column_width=True)

# Select starting node
start_node = st.selectbox("Select starting node:", list(graph.keys()), index=0)

# Run DFS when button clicked
if st.button("Run DFS Traversal"):
    result = dfs(graph, start_node)
    st.success(f"**DFS Traversal starting from '{start_node}':**")
    st.write(" → ".join(result))

    # Show step-by-step traversal
    st.subheader("Traversal Process (Step-by-Step)")
    for i, node in enumerate(result, 1):
        st.write(f"**Step {i}:** Visit {node}")

# Display the graph structure
st.subheader("Graph Structure (Adjacency List)")
for node, neighbors in graph.items():
    st.write(f"**{node}** → {', '.join(neighbors) if neighbors else '(no neighbors)'}")

st.caption("Developed for Search Algorithms Lab — DFS Example")